<?php require_once "../app/views/navbar.phtml" ?>



<div class="container">

    <div class="row py-5">

        <div class="col-md-12 mx-auto text-center">

            <span class="display-4"">Perfil</span>
            <blockquote class="blockquote text-muted">Deletar perfil</blockquote>

        </div>

    </div>

    <div class="row">

        <div class="col-md-8 mx-auto border rounded">

            <div class="row mt-4">

                <div class="col text-center">

                    <p>A conta foi apagada permanentemente.</p>
                    <a href="/inicio" class="btn btn-dark">Voltar</a>

                </div>

            </div>

        </div>

    </div>

</div>
