<?php require_once "../app/views/navbar.phtml" ?>

<div class="container">

    <div class="row my-5">

        <div class="col-md-12 mx-auto text-center">

            <span class="display-4"">Perfil</span>
            <blockquote class="blockquote text-muted">Adicione ou modifique informações sobre você</blockquote>

        </div>

    </div>

        <?php if(isset($_GET['status']) && $_GET['status'] == 1) { ?>

            <div class="alert alert-success alert-dismissible fade show text-center mt-5" role="alert">
                <h4>As alterações foram realizadas com sucesso.</h4> 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>

        <?php } else if(isset($_GET['status']) && $_GET['status'] == 2) { ?>

            <div class="alert alert-danger alert-dismissible fade show text-center mt-5" role="alert">
                <h4>Já existe um usuário com o e-mail solicitado.</h4> 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>

        <?php } ?>

    <div class="row mb-5">

        <div class="col-md-8 mx-auto border shadow bg-white rounded">

            <div class="row mt-4">

                <div class="col text-center">

                    <p class="title"><?php echo $_SESSION['nome'] . ' '; echo $_SESSION['sobrenome'] ?></p>
                    <p class="subtitle text-muted font-italic"><?= $this->tipo['cargo'] ?></p>

                </div>

            </div>

            <div class="row mt-4">

                <div class="col">

                    <form action="/alterarPerfil" method="post" >

                        <input id="id" name="id" type="text" value="<?=$_SESSION['id']?>" hidden>

                        <div class="form-row">

                            <div class="form-group col-md-6">
                                <label for="nome">Nome</label>
                                <input type="text" class="form-control" id="nome" name="nome" maxlength="40" value="<?= $_SESSION['nome'] ?>">
                            </div>

                            <div class="form-group col-md-6">
                                <label for="sobrenome">Sobrenome</label>
                                <input type="text" class="form-control" id="sobrenome" name="sobrenome" maxlength="40" value="<?= $_SESSION['sobrenome'] ?>">
                            </div>

                        </div>

                        <div class="form-row">

                            <div class="form-group col-md-12">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" name="email" id="email" maxlength="60" value="<?= $_SESSION['email'] ?>" >
                            </div>

                        </div>

                        <div class="form-row">

                            <div class="form-group col-md-6">
                                <label for="cel">Celular</label>
                                <input type="text" class="form-control" id="cel" name="cel" maxlength="15" value="<?= $_SESSION['cel'] ?>" placeholder="(00) 00000-0000">
                            </div>

                            <div class="form-group col-md-6">
                                <label for="cel">Telefone</label>
                                <input type="text" class="form-control" id="tel" name="tel" maxlength="14" value="<?= $_SESSION['tel'] ?>" placeholder="(00) 0000-0000">

                            </div>

                        </div>


                        <div class="row my-3">

                            <div class="col-sm-4 col-md-4">
                                <hr>
                            </div>

                            <div class="col-sm-4 col-md-4 text-center">
                                <span class="subtitle text-muted">Alterar senha</span>
                            </div>

                            <div class="col-sm-4 col-md-4">
                                <hr>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col text-center">
                                <p class="text-muted">Para que a senha seja alterada, ambos os campos devem estar preenchidos corretamente.</p>
                            </div>
                        </div>

                        <div class="form-row">

                            <div class="form-group col-md-6">
                                <div class="input-group">
                                    <input type="password" class="form-control" name="senha" id="senha" maxlength="100" placeholder="Senha atual">
                                    <div class="input-group-append">
                                        <button type="button" class="btn btn-light btn-sm border" data-toggle="button" aria-pressed="false" onclick="mostrarSenha('senha')">Mostrar</button>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-md-6">
                                <div class="input-group">
                                    <input type="password" class="form-control" name="senhanova" id="senhanova" maxlength="100" placeholder="Nova senha">
                                    <div class="input-group-append">
                                        <button type="button" class="btn btn-light btn-sm border" data-toggle="button" aria-pressed="false" onclick="mostrarSenha('senhanova')">Mostrar</button>
                                    </div>
                                </div>
                            </div>

                            <script>
                            
                                function mostrarSenha(id) {
                                    var tipo = document.getElementById(id)
                                    if(tipo.type == "password"){
                                        tipo.type = "text"
                                    } else {
                                        tipo.type = "password"
                                    }
                                }

                            </script>

                        </div>

                        <?php if($this->view->erroAlterar) { ?>

                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>Erro na validação dos dados!</strong> 
                            <br>
                            Verifique se os campos foram preenchidos corretamente.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>

                        <?php } ?>

                        <div class="form-row mt-3">

                            <div class="form-group col-md-12 text-center">
                                <button type="submit" class="btn w-25 btn-dark">Salvar</button>
                            </div>

                        </div>

                    </form>

                    <?php if($_SESSION['tipo'] == 1) { ?>

                        <div class="row my-3">

                            <div class="col-sm-4 col-md-4">
                                <hr>
                            </div>

                            <div class="col-sm-4 col-md-4 text-center">
                                <span class="subtitle text-muted">Deletar conta</span>
                            </div>

                            <div class="col-sm-4 col-md-4">
                                <hr>
                            </div>

                        </div>

                        <form action="/deletarPerfil" method="post" >
                            <div class="form-row">
                                <div class="col-md-12 text-center">
                                    <p class="text-danger">Ao realizar esta ação todos os dados pertinentes a essa conta será purgado do servidor, não sendo possível reverter essa situação.</p>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12 text-center">
                                    <button type="submit" class="btn w-25 btn-outline-danger">Deletar</button>
                                </div>
                            </div>
                        </form>

                    <?php } ?> 

                </div>

            </div>

        </div>

    </div>

</div>

<script>

    $('#cel').maskbrphone({  
        useDdd           : true,
        useDddParenthesis: true,
        dddSeparator     : ' ',
        numberSeparator  : '-'
    });

    $('#tel').maskbrphone({  
        useDdd           : true,
        useDddParenthesis: true,
        dddSeparator     : ' ',
        numberSeparator  : '-'
    });

</script>