<body class="bg-danger">
<div class="container">
  <div class="d-flex justify-content-center my-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/logo-ifsp.png" class="logo" />
        </div>

        <div class="row pl-5 pr-5 py-3">
						<div class="col mx-auto text-center">
            <h3 class="title">Cadastro realizado com sucesso!</h3>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/" class="btn btn-danger btn-block py-2">Clique aqui para fazer login!</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  