<?php require_once "../app/views/navbar.phtml" ?>
<style>
    a:hover {
        filter: brightness(0.75);
    }
</style>
<div class="container">

    <div class="row my-5">

        <div class="col-md-12 mx-auto text-center">

            <span class="display-4"">Estudantes</span>
            <blockquote class="blockquote text-muted">Lista de todos os estudantes cadastrados</blockquote>

        </div>

    </div>

    <div class="row mb-5">

        <div class="col-auto mx-auto px-auto border shadow bg-white rounded text-center py-3">
            
            

        </div>

    </div>

</div>