<?php require_once "../app/views/navbar.phtml" ?>
<style>
    a:hover {
        filter: brightness(0.75);
    }
</style>
<div class="container">

    <div class="row my-5">

        <div class="col-md-12 mx-auto text-center">

            <span class="display-4"">Estudantes</span>
            <blockquote class="blockquote text-muted">Lista de todos os estudantes cadastrados</blockquote>

        </div>

    </div>

    <div class="row mb-5">

        <div class="col-auto mx-auto px-auto border shadow bg-white rounded text-center py-3">
            
            <table id="estudantes" class="table table-striped table-hover table-responsive">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Ação</th>
                        <th scope="col">Nome</th>
                        <th scope="col">E-mail</th>
                        <th scope="col">Celular</th>
                        <!-- <th scope="col">Telefone</th> -->
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->estudantes as $key => $estudante) { ?>
                    <tr>
                        <th scope="row"><?= $estudante['id']?></th>
                        <td>
                            <a alt="Deletar usuário" href="/deletarPerfil?id=<?=$estudante['id']?>">
                                <i class="fas fa-user-slash text-danger mx-2"></i>
                            </a>
                            <a href="/estudante?id=<?=$estudante['id']?>">
                                <i class="fas fa-edit text-warning mx-2"></i>
                            </a>
                        </td>
                        <td><?= $estudante['nome']?> <?= $estudante['sobrenome']?></td>
                        <td><?= $estudante['email']?></td>
                        <td><?= $estudante['cel']?></td>
                        <!-- <td><?= $estudante['tel']?></td> -->
                    </tr>
                    <?php } ?>
                </tbody>
            </table>

        </div>

    </div>

</div>

<script>
    $(document).ready(function() {
        $('#estudantes').DataTable( {
            "columnDefs": [
                    { "orderable": false, "targets": 1},
                    { "orderable": false, "targets": 3}
                ],
            "language": {
                "lengthMenu": "Mostrando _MENU_ registros por página",
                "zeroRecords": "Nenhum Registro Encontrado",
                "info": "Total de _MAX_ estudante(s), mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "Nenhum registro Disponível",
                "infoFiltered": "",
                "search": "Busca:",
                "pagingType": "full_numbers",
                "paginate": {
                    "next": "Próximo",
                    "previous": "Anterior"
                }
            }
        } );
    } );
</script>
