<?php require_once "../app/views/navbar.phtml" ?>

<div class="container">

	<div class="row mt-5">

		<div class="col-md-12 text-center">

			<span class="display-4">Cursos</span>

		</div>

	</div>

    <?php             
        $novarow = 0;
        foreach($this->cursos as $i => $curso) {
            if($curso['status']) {
                if($i == $novarow) { 
    ?>

                <div class="row">
            
    <?php 
                }
    ?>
                <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 my-5">
                    <div class="card shadow bg-light rounded h-auto">
                        <?php if($this->tipo['numero'] >= 2){ ?>
                            <p class="text-muted text-center mx-auto my-2"><?= $curso['id'] ?></p>
                        <?php } if(file_exists('img/'.$curso['img'].'.jpg')){?>
                            <a class="curso-img" href="/curso?id=<?= $curso['id']?>">
                                <img class="card-img-top" src="img/<?= $curso['img']?>.jpg" alt="<?php $curso['curso'] ?>">
                            </a>
                        <?php } ?>
                        <div class="card-body">
                            <h5 class="card-title"><?= $curso['curso'] ?> </h5>
                            <blockquote class="text-muted"><?= $curso['nome'] ?> <?= $curso['sobrenome'] ?></blockquote>
                            <p class="card-text crop-text"><?= $curso['descricao'] ?></p>
                            <a href="/curso?id=<?= $curso['id']?>" class="btn btn-dark align-text-bottom">Estudar</a>
                            
                        </div>
                    </div>
                </div>

    <?php
                if(($i-3) == $novarow) {
                $novarow += 4;
    ?>
                </div>   
    <?php
                }
            } else {
                $novarow += 1;
            }
        }
    ?>
    
		


</div>